import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav";
import PageTransition from "../components/PageTransition";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <body className="antialiased bg-background text-foreground">
        <Nav />
        <PageTransition>
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
